export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    ONBOARDING: '/onboarding',
    REGISTRATION: '/registration',
    USER: '/user',
    ACCOUNT: '/user/account',
    ORDERS: '/user/orders',
    BETS: '/user/bets',
    ADVERTISEMENT: '/user/advertisements',
    LOTSLIST: '/lotslist',
    LOTVIEW: '/lotslist/lotview',
    ADMIN: '/admin',
    ADMINUSERS: '/admin/users',
    ADMINCREATEUSER: '/admin/users/create',
    ADMINBETS: '/admin/bets',
    ADMINACCOUNT: '/admin/account',
    USERINFO: '/admin/users/:id',
    ADDLOT: '/addlot',
    PREVIEW: '/addlot/preview',
    SUCCESSADD: '/addlot/success',
    FAILEDADD: '/addlot/failed',
    FINISHADD: '/addlot/finish'
}
